"""Add user profile fields

Revision ID: 32500f6f005b
Revises: aa8af198b9de
Create Date: 2025-09-17 00:45:49.902746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32500f6f005b'
down_revision = 'aa8af198b9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resume_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('resume_filename')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('target_role')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
