"""init updated schema

Revision ID: 602dd1b48aee
Revises: 32500f6f005b
Create Date: 2025-09-23 02:34:55.194087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602dd1b48aee'
down_revision = '32500f6f005b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signature_ok', sa.Boolean(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('interview_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_turns_interview_id'), ['interview_id'], unique=False)

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_type_used', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_hash', sa.String(length=64), nullable=True))
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('reset_token_hash')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('credit_type_used')

    with op.batch_alter_table('interview_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_turns_interview_id'))

    op.drop_table('interview_turns')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
